/* ════════════════════════════════════════════════════════
   services-data.js — Gribouille Event Lab
   Services affichés sur index.html (showOnIndex:true) et services.html (tous)
 Généré automatiquement
════════════════════════════════════════════════════════ */

const SERVICES_DEFAULTS = [
  {
    title:       "Design 3D & Structure scénique",
    text:        "Du concept à la réalisation, nous créons des structures scéniques sur mesure qui définissent l'identité visuelle de votre événement.",
    icon:        "img/icones/IMG_8127.webp",
    showOnIndex: true,
    id:          "design",
    label:       "Structures & Architecture",
    fullTitle:   "Design 3D & Structures Sur-Mesure",
    description: "Du croquis conceptuel à la réalité fabriquée — scènes, arches, totems et éléments scéniques sur-mesure qui deviennent l'identité visuelle de votre événement. Chaque structure est conçue pour la sécurité et pensée pour l'impact.",
    deliverables: [
      "Structures de scène, arches, Grills & totems",
      "Plans CAD et rendus 3D avant fabrication",
      "Éléments scéniques bois & matériaux mixtes",
      "Certification de sécurité et de charge, par un bureau d'étude externe.",
      "Constructions et installations temporaires ou permanentes",
    ],
    image:       "img/projects/vectorworks--stage/Sans_Titre_1.webp",
    imageAlt:    "3D structure design for festival stage",
  },
  {
    title:       "Production Technique",
    text:        "Gestion technique complète du repérage à la validation finale — logistique, rigging, électrique et coordination d'équipes.",
    icon:        "img/icones/IMG_8124.webp",
    showOnIndex: true,
    id:          "technical",
    label:       "Dans les Coulisses",
    fullTitle:   "Production Technique",
    description: "Gestion technique complète du repérage à la validation finale. On coordonne la logistique, les équipes, le rigging et la distribution électrique pour que votre vision créative se réalise en sécurité, dans les temps et dans le budget.",
    deliverables: [
      "Repérage de site & préparation de rider technique",
      "Plans de rigging et structures en hauteur",
      "Distribution électrique et gestion des câbles",
      "Calage d'un système sonore",
      "Mapping vidéo",
      "Programmation DMX",
      "Gestion du montage / démontage",
      "Documentation sécurité & conformité",
    ],
    image:       "img/media/Image/20260327_130830.webp",
    imageAlt:    "Technical crew rigging festival stage",
  },
  {
    title:       "Aménagement Club & Bar",
    text:        "Scénographie intérieure permanente — architecture personnalisée, éclairage d'ambiance et identité spatiale forte.",
    icon:        "img/icones/IMG_8123.webp",
    showOnIndex: true,
    id:          "fitout",
    label:       "Espaces Permanents",
    fullTitle:   "Aménagement Bar & Club",
    description: "Votre lieu mérite mieux qu'un coup de peinture. On conçoit et installe des identités spatiales permanentes et semi-permanentes pour clubs, bars et espaces culturels — structures sur-mesure, systèmes d'éclairage d'ambiance et concepts visuels qui définissent votre marque en trois dimensions.",
    deliverables: [
      "Concept complet de design scénique intérieur",
      "Structures de bar et mobilier sur-mesure",
      "Installations permanentes plafond et murs",
      "Systèmes d'éclairage d'ambiance et d'atmosphère",
      "Identité visuelle de marque dans l'espace",
      "Forfaits maintenance et mise à jour disponibles",
    ],
    image:       "img/media/Image/pexels-amelia-hallsworth-5461566.webp",
    imageAlt:    "Club interior installation and lighting",
  },
  {
    title:       "Direction Artistique",
    text:        "Direction créative de bout en bout — moodboards, rendus 3D, choix des matières et vision artistique globale de votre événement.",
    icon:        "img/icones/IMG_8122.webp",
    showOnIndex: true,
    id:          "concept",
    label:       "Direction Créative",
    fullTitle:   "Concept & Direction Artistique",
    description: "Parfois vous avez une sensation, pas encore un brief. On vous aide à trouver les mots et les images — puis on construit le plan pour le rendre réel. On vous emmène de l'étincelle au projet entièrement spécifié, prêt pour la production.",
    deliverables: [
      "Développement du brief créatif",
      "Moodboards et direction visuelle",
      "Rendus 3D du concept proposé",
      "Spécifications des matières, finitions et couleurs",
      "Planification budgétaire et phasage",
      "Coordination fournisseurs et partenaires",
    ],
    image:       "img/media/DA/IMG_8081_1_.webp",
    imageAlt:    "Art direction moodboard and concept sketches",
  },
  {
    title:       "Fabrication & Décors",
    text:        "Soudure, menuiserie, fabrication structurelle et décors sur mesure — entièrement fabriqués par nous dans notre atelier.",
    icon:        "img/icones/IMG_8125.webp",
    showOnIndex: true,
    id:          "fabrication",
    label:       "L'Atelier",
    fullTitle:   "Fabrication & Construction",
    description: "On fabrique des décors. Depuis notre atelier bruxellois, on découpe, soude, peint, capitonne et construit les éléments qui composent nos installations.",
    deliverables: [
      "Soudure acier et aluminium (MIG/TIG)",
      "Menuiserie et travail du bois",
      "Découpe CNC et formes sur-mesure",
      "Traitements peinture, texture et finition",
      "Accessoires scéniques et mobilier sur-mesure",
      "Fabrication de prototypes et pièces uniques",
    ],
    image:       "img/media/Photos/IMG_9928.webp",
    imageAlt:    "Fabrication workshop — welding and woodwork",
  },
  {
    title:       "Gestion des Fournisseurs",
    text:        "Un seul interlocuteur pour l'ensemble des prestataires — coordination complète de A à Z.",
    icon:        "img/icones/IMG_8120.webp",
    showOnIndex: true,
    id:          "gestion",
    label:       "Gestion",
    fullTitle:   "Gestion des Fournisseurs",
    description: "On s'occupe de tout — de A à Z. Grâce à notre réseau de partenaires spécialisés, Gribouille Event Lab coordonne l'ensemble des intervenants à votre place. Un seul interlocuteur, zéro stress.",
    deliverables: [
      "Coordination d'équipe interne",
      "Gestion des prestataires externes",
      "Matériel technique et structurel",
      "Transport & livraison sur site",
      "Logistique complète de l'événement",
    ],
    image:       "img/media/Image/pexels-erik-debarre-2151386688-33890525.webp",
    imageAlt:    "Event management and logistics",
  },
];